### ISSUE TITLE
Create Website Logo

### ISSUE THREAD

**Issue by xttrust** [xttrust/HolyRecipes#5]
Create a logo for our project. Use [Canva](https://canva.com/) since is free and easy to use.

**Comment by SamMartin92** [comment]
Of the logos Joanne presented in Slack, I prefer the choices with no double lines. But those with double lines, still look good to me

**Comment by xttrust** [comment]
Wich logo you guys choose I go along. They all look good.

**Comment by xttrust** [comment]
joanne created the logo, so this issue is now closed.
